apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "dotnetapp.fullname" . }}
  labels:
    {{- include "dotnetapp.labels" . | nindent 4 }}
spec:
  replicas: 2
  selector:
    matchLabels:
      {{- include "dotnetapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels:
        {{- include "dotnetapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: {{ .Chart.Name }}
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag | default .Chart.AppVersion }}"
        ports:
        - containerPort: 80
          protocol: TCP